package provider

import (
	"context"
	"fmt"

	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/path"
	"github.com/hashicorp/terraform-plugin-framework/resource"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringdefault"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"

	"github.com/quarks-tech/terraform-provider-kener/internal/client"
)

var maintenanceStatuses = []string{"ACTIVE", "INACTIVE"}

var (
	_ resource.Resource                = (*maintenanceResource)(nil)
	_ resource.ResourceWithConfigure   = (*maintenanceResource)(nil)
	_ resource.ResourceWithImportState = (*maintenanceResource)(nil)
)

// NewMaintenanceResource is the resource constructor registered with the provider.
func NewMaintenanceResource() resource.Resource {
	return &maintenanceResource{}
}

type maintenanceResource struct {
	client *client.Client
}

type maintenanceResourceModel struct {
	ID              types.String `tfsdk:"id"`
	Title           types.String `tfsdk:"title"`
	Description     types.String `tfsdk:"description"`
	StartDateTime   types.Int64  `tfsdk:"start_date_time"`
	RRule           types.String `tfsdk:"rrule"`
	DurationSeconds types.Int64  `tfsdk:"duration_seconds"`
	Status          types.String `tfsdk:"status"`
	Monitors        types.List   `tfsdk:"monitors"`
	URL             types.String `tfsdk:"url"`
}

func (r *maintenanceResource) Metadata(_ context.Context, req resource.MetadataRequest, resp *resource.MetadataResponse) {
	resp.TypeName = req.ProviderTypeName + "_maintenance"
}

func (r *maintenanceResource) Schema(_ context.Context, _ resource.SchemaRequest, resp *resource.SchemaResponse) {
	resp.Schema = schema.Schema{
		MarkdownDescription: "Manages a Kener scheduled-maintenance window. The schedule is an iCalendar RRULE plus a duration; individual occurrences (events) are generated by Kener and are not managed here.",
		Attributes: map[string]schema.Attribute{
			"id": schema.StringAttribute{
				MarkdownDescription: "Numeric identifier assigned by Kener.",
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"url": schema.StringAttribute{
				MarkdownDescription: "Absolute public URL of the maintenance.",
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
			},
			"title": schema.StringAttribute{
				MarkdownDescription: "Maintenance title.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtLeast(1)},
			},
			"description": schema.StringAttribute{
				MarkdownDescription: "Optional description.",
				Optional:            true,
			},
			"start_date_time": schema.Int64Attribute{
				MarkdownDescription: "Start time as a Unix timestamp (seconds). Kener aligns this to the minute.",
				Required:            true,
			},
			"rrule": schema.StringAttribute{
				MarkdownDescription: "Recurrence rule in iCalendar RRULE format, e.g. `FREQ=WEEKLY;BYDAY=SU`.",
				Required:            true,
				Validators:          []validator.String{stringvalidator.LengthAtLeast(1)},
			},
			"duration_seconds": schema.Int64Attribute{
				MarkdownDescription: "Duration of each maintenance occurrence, in seconds (at least 1).",
				Required:            true,
				Validators:          []validator.Int64{int64validator.AtLeast(1)},
			},
			"status": schema.StringAttribute{
				MarkdownDescription: "Whether the maintenance is enabled. One of `ACTIVE`, `INACTIVE`. Defaults to `ACTIVE`.",
				Optional:            true,
				Computed:            true,
				PlanModifiers:       []planmodifier.String{stringplanmodifier.UseStateForUnknown()},
				Validators:          []validator.String{stringvalidator.OneOf(maintenanceStatuses...)},
			},
			"monitors": schema.ListNestedAttribute{
				MarkdownDescription: "Monitors affected by this maintenance, with their impact.",
				Optional:            true,
				Computed:            true,
				PlanModifiers:       []planmodifier.List{listplanmodifier.UseStateForUnknown()},
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"monitor_tag": schema.StringAttribute{
							MarkdownDescription: "Tag of the affected monitor.",
							Required:            true,
						},
						"impact": schema.StringAttribute{
							MarkdownDescription: "Impact on the monitor. One of `UP`, `DOWN`, `DEGRADED`, `MAINTENANCE`. Defaults to `MAINTENANCE`.",
							Optional:            true,
							Computed:            true,
							Default:             stringdefault.StaticString("MAINTENANCE"),
							Validators:          []validator.String{stringvalidator.OneOf(impactLevels...)},
						},
					},
				},
			},
		},
	}
}

func (r *maintenanceResource) Configure(_ context.Context, req resource.ConfigureRequest, resp *resource.ConfigureResponse) {
	if req.ProviderData == nil {
		return
	}
	c, ok := req.ProviderData.(*client.Client)
	if !ok {
		resp.Diagnostics.AddError("Unexpected Resource Configure Type",
			fmt.Sprintf("Expected *client.Client, got: %T. Please report this issue to the provider developers.", req.ProviderData))
		return
	}
	r.client = c
}

func modelToMaintenance(ctx context.Context, m *maintenanceResourceModel) (*client.Maintenance, diag.Diagnostics) {
	monitors, diags := monitorsToClient(ctx, m.Monitors)
	mm := &client.Maintenance{
		Title:           m.Title.ValueString(),
		Description:     strPtr(m.Description),
		StartDateTime:   int64Ptr(m.StartDateTime),
		RRule:           m.RRule.ValueString(),
		DurationSeconds: int64Ptr(m.DurationSeconds),
		Monitors:        monitors,
	}
	if !m.Status.IsNull() && !m.Status.IsUnknown() {
		mm.Status = m.Status.ValueString()
	}
	return mm, diags
}

// applyMaintenance copies the server's view onto the model, leaving
// start_date_time to the caller (Kener minute-aligns it; see incident).
func applyMaintenance(ctx context.Context, mm *client.Maintenance, m *maintenanceResourceModel) diag.Diagnostics {
	m.ID = types.StringValue(mm.ID.String())
	m.Title = types.StringValue(mm.Title)
	m.Description = strValue(mm.Description)
	m.RRule = types.StringValue(mm.RRule)
	m.DurationSeconds = int64Value(mm.DurationSeconds)
	m.Status = types.StringValue(mm.Status)
	m.URL = types.StringValue(mm.URL)
	list, diags := monitorsToModel(ctx, mm.Monitors)
	m.Monitors = list
	return diags
}

func (r *maintenanceResource) Create(ctx context.Context, req resource.CreateRequest, resp *resource.CreateResponse) {
	var plan maintenanceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload, diags := modelToMaintenance(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}

	created, err := r.client.CreateMaintenance(ctx, payload)
	if err != nil {
		resp.Diagnostics.AddError("Error creating maintenance", fmt.Sprintf("Could not create maintenance %q: %s", plan.Title.ValueString(), err))
		return
	}

	// status is ignored on create; apply it with a follow-up update if the
	// desired value differs from the server default.
	result := created
	if !plan.Status.IsNull() && !plan.Status.IsUnknown() && plan.Status.ValueString() != created.Status {
		result, err = r.client.UpdateMaintenance(ctx, created.ID.String(), payload)
		if err != nil {
			resp.Diagnostics.AddError("Error setting maintenance status", fmt.Sprintf("Maintenance %s was created but its status could not be set: %s", created.ID.String(), err))
			return
		}
	}

	resp.Diagnostics.Append(applyMaintenance(ctx, result, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *maintenanceResource) Read(ctx context.Context, req resource.ReadRequest, resp *resource.ReadResponse) {
	var state maintenanceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	got, err := r.client.GetMaintenance(ctx, state.ID.ValueString())
	if err != nil {
		if client.IsNotFound(err) {
			resp.State.RemoveResource(ctx)
			return
		}
		resp.Diagnostics.AddError("Error reading maintenance", fmt.Sprintf("Could not read maintenance %q: %s", state.ID.ValueString(), err))
		return
	}
	resp.Diagnostics.Append(applyMaintenance(ctx, got, &state)...)
	// Seed start_date_time from the server only on import (no prior value).
	if state.StartDateTime.IsNull() {
		state.StartDateTime = int64Value(got.StartDateTime)
	}
	resp.Diagnostics.Append(resp.State.Set(ctx, &state)...)
}

func (r *maintenanceResource) Update(ctx context.Context, req resource.UpdateRequest, resp *resource.UpdateResponse) {
	var plan maintenanceResourceModel
	resp.Diagnostics.Append(req.Plan.Get(ctx, &plan)...)
	if resp.Diagnostics.HasError() {
		return
	}
	payload, diags := modelToMaintenance(ctx, &plan)
	resp.Diagnostics.Append(diags...)
	if resp.Diagnostics.HasError() {
		return
	}
	updated, err := r.client.UpdateMaintenance(ctx, plan.ID.ValueString(), payload)
	if err != nil {
		resp.Diagnostics.AddError("Error updating maintenance", fmt.Sprintf("Could not update maintenance %q: %s", plan.ID.ValueString(), err))
		return
	}
	resp.Diagnostics.Append(applyMaintenance(ctx, updated, &plan)...)
	resp.Diagnostics.Append(resp.State.Set(ctx, &plan)...)
}

func (r *maintenanceResource) Delete(ctx context.Context, req resource.DeleteRequest, resp *resource.DeleteResponse) {
	var state maintenanceResourceModel
	resp.Diagnostics.Append(req.State.Get(ctx, &state)...)
	if resp.Diagnostics.HasError() {
		return
	}
	if err := r.client.DeleteMaintenance(ctx, state.ID.ValueString()); err != nil {
		if client.IsNotFound(err) {
			return
		}
		resp.Diagnostics.AddError("Error deleting maintenance", fmt.Sprintf("Could not delete maintenance %q: %s", state.ID.ValueString(), err))
	}
}

func (r *maintenanceResource) ImportState(ctx context.Context, req resource.ImportStateRequest, resp *resource.ImportStateResponse) {
	resource.ImportStatePassthroughID(ctx, path.Root("id"), req, resp)
}
